apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-csi-cstor
